ROOT_DIR := ../..

.PHONY: help framework generate simulator device device-logs build test run \
	run-regtest test-regtest clean

help framework generate simulator device device-logs build test run run-regtest \
	test-regtest clean:
	@$(MAKE) -C "$(ROOT_DIR)" --no-print-directory $@
